services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: hausmeister
      POSTGRES_USER: hausmeister
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis/redis-stack-server:6.2.6-v4
    restart: always
    ports:
      - 6379:6379
      
  
