services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: hausmeister
      POSTGRES_USER: hausmeister
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis/redis-stack-server:6.2.6-v4
    restart: always
    ports:
      - 6379:6379

  hausmeister:
    environment:
      RUST_BACKTRACE: 0
      RUST_LOG: "debug,hausmeister=trace"
      HM_APP__LISTEN: "::"
      HM_REDIS__URL: "redis://redis/"
      HM_DATABASE__URL: "psql://hausmeister:password@db/"
    ports:
      - 3779:3779
    build: "."
    init: true
 
