services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: hausmeister
      POSTGRES_USER: hausmeister
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  
